weni-ai/weni-integrations-webapp

- .github/workflows/build-integrations-webapp-dispatch-shared.yaml
- .github/workflows/build-integrations-webapp-push-tag-shared.yaml
The modifications will prevent insert a tag with an old version of an image and automaticaly deploy in kubernetes cluster.
> Add workflow protection to prevent deploy old image

- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/WWC/Simulator.vue
Backed was expecting `showFullScreenButton` but `showFullscreenButton` was being sent instead.
> Fix: showfullScreenButton not working due to case typo

- src/components/config/channels/whatsapp/components/tabs/AccountTab.vue
- tests/unit/specs/components/config/channels/whatsapp/components/StatusIndicator.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/__snapshots__/StatusIndicator.spec.js.snap
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/__snapshots__/AccountTab.spec.js.snap
Removed mocked status indicator from Account tab, since backend support is not yet complete
> Fix: Removed mocked status indicator

- src/components/LoadingButton.vue
- src/store/appType/channels/whatsapp_cloud/mutations.js
- src/store/appType/mutations.js
- tests/unit/specs/components/app/__snapshots__/AppDetailsHeader.spec.js.snap
The error state was not being cleared before another request was made, making successful future requests trigger the error state.
> fix: unable to add other apps after one fails

- src/api/appType/whatsapp/index.js
- src/store/appType/channels/whatsapp/actions.js
- src/store/appType/channels/whatsapp/getters.js
- src/store/appType/channels/whatsapp/mutations.js
- src/store/appType/channels/whatsapp/state.js
- tests/unit/specs/store/appType/whatsapp/actions.spec.js
- tests/unit/specs/store/appType/whatsapp/getters.spec.js
Store related to WhatsApp template form management and data fetch/update.
- New Actions
- updateTemplateForm
- addNewTranslationForm
- renameTemplateTranslationForm
- updateTemplateTranslationForm
- setTemplateTranslationSelectedForm
- clearAllTemplateFormData
- fetchTemplateData
- fetchSelectLanguages
- createTemplate
- createTemplateTranslation
- deleteTemplateMessage
- New getter
- templateTranslationCurrentForm
> Feat: WhatsApp Templates Vuex store

- src/components/config/channels/WWC/Config.vue
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- Fixed misuse of `getApp` action
> Fix: WeniWebChat saveConfig incorrect error

- src/components/whatsAppTemplates/FormTabContentBody.vue
- When some language extensions are utilized in the browser, the input component is changed and the `textarea` child index is different from zero. Now we search based on the `nodeName` in the children list, avoiding that issue.
> Fix: Find text-area element based on node name and not index

- src/components/AppGrid.vue
- When grid size was too small `maxWidthItems` became zero due to `Math.floor` and caused zero division errors in other methods causing memory issues in browser tab. 
- Removed lodash.throttle
> Fix: Discovery page memory issue

- src/components/config/channels/whatsapp/Config.vue
- src/components/config/channels/whatsapp/components/tabs/AccountTab.vue
- Set a maximum height for WhatsApp tabs to be able to use the scroll on firefox
- Set `word-wrap: anywhere` on account table fields to prevent horizontal scroll
> fix: wpp tabs scroll on firefox and horizontal wrap

- src/api/appType/whatsapp/index.js
- src/components/whatsAppTemplates/FormTabContent.vue
- src/components/whatsAppTemplates/FormTabContentButtons.vue
- src/components/whatsAppTemplates/FormTabs.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- src/store/appType/channels/whatsapp/actions.js
- src/store/appType/channels/whatsapp/mutations.js
- src/store/appType/channels/whatsapp/state.js
- tests/unit/specs/components/whatsAppTemplates/FormTabContent.spec.js
- tests/unit/specs/components/whatsAppTemplates/FormTabs.spec.js
- tests/unit/specs/store/appType/whatsapp/actions.spec.js
- Added option to edit WhatsApp templates, using the message_template_id from the translations as the identifier
- Only allow edit behavior when the template is APPROVED or REJECTED
> Feat: Edit WhatsApp Templates

- src/components/whatsAppTemplates/Table.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- tests/unit/specs/components/whatsAppTemplates/Table.spec.js
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/Table.spec.js.snap
- Use the larger datepicker instead of small one to be able to clear the dates
> Fix: WhatsApp Templates date picker

- src/components/AppGrid.vue
- tests/unit/specs/views/__snapshots__/MyApps.spec.js.snap
WhatsApp integration UUID copy icon was incorrect. Changed to "copy-paste" icon.
> Fix: Copy UUID icon

- src/components/whatsAppCatalogs/Card.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
Update “Enable” and “Disable” texts to “Activate” and “Disable” on the catalog listing screens and modals according to the file in the [Figma](https://www.figma.com/file/VlFAkXsSOiYqVhvpaa3Y9a/Cat%C3%A1logo-WPP?type=design&node-id=3031%3A20607&mode=design&t=7VdmyyV5tcGUsSe2-1)
> [FLOWS-126] Feat: update switch label

- src/components/config/external/chatgpt/Setup.vue
- tests/unit/specs/components/config/external/chatgpt/__snapshots__/Setup.spec.js.snap
- Modal was overflowing instead of adding a scroll into the content, now a scroll appears when the height is not enough to show the content
> [FLOWS-228] Fix: ChatGPT modal height

- src/components/config/channels/whatsapp/components/tabs/AccountTab.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
In the WhatsApp connect catalog process, the Vtex app was not being assigned, making it unable to connect a new catalog
Moved Vtex app variable assignment to be outside the if statement.
> fix: always fetch vtexApp in whatsapp account tab

- src/components/whatsAppTemplates/Table.vue
- src/components/whatsAppTemplates/TableActionButton.vue
- tests/unit/specs/components/whatsAppTemplates/Table.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Whatsapp templates table wasn`t adjusting the heigh to fit full page.
At class .scroll: changed flex to none and set a fixed height of 50vh.
> Fix: whatsapp templates - table height

- src/components/config/channels/facebook/Setup.vue
Add required business-management permission into facebook login process for Facebook and Instagram applications
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Users are not able to proceed with the Facebook/Instagram integration.
Added new business-management permission
> fix: add business management permission to fb login

- CHANGELOG.md
- package.json
- src/components/whatsAppTemplates/FormTabContentBody.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Allow the use of a variable at the beginning and the end of the body.
Remove rules that block the use of variables at the beginning and end of the body.
> [FLOWS - 2422] Allow the use of a variable at the beginning and the end of the body.

- src/tests/views/__snapshots__/OtherApps.spec.js.snap
- src/views/OtherApps/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Now weni flows authenticate with a token as a query parameter and uses the project_uuid instead of flow_org_uuid
Added token and project_uuid into the generated url
> Update iframe source in OtherApps component to use dynamic project and token values

- src/utils/env.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
In order to solve the hotjar integration problem, where it tried to access the `HOTJAR_ID` variable by omitting the `VITE_APP_` prefix, this PR aims to introduce the possibility of accessing environment variables by omitting the `VITE_APP_` prefix, making environment variables accessible in both ways, with or without the `VITE_APP_` prefix.
* adds the possibility to access the environment variable also omitting the prefix `VITE_APP_`.
> [HS-983] Multiple Ways to Access Environment Variables

- src/components/config/channels/facebook/Setup.vue
* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
Add new permission to allow IG channels to reply to comments
Added new permission in IG app scope permission list
> fix: add 'instagram_manage_comments' scope to Facebook app permissions

- src/components/config/channels/WWC/Config.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
Select time had the time format based on the user browser language, so english users had the AM/PM variant, this as an issue since the contactTimeout is a timer and not a time
- Replaced unnnic-select-time with unnnic-input for contact timeout input.
- Added validation for contact timeout format, ensuring it adheres to HH:mm and does not exceed 24 hours.
- Updated button state to disable when the contact timeout is invalid or while saving.
- Localized error message for invalid contact timeout in English, Spanish, and Portuguese.
> feat: enhance contact timeout validation in WWC configuration
