weni-ai/weni-integrations-webapp

- src/api/appType.js
- src/components/AppGrid.vue
- src/components/app/AppDetailsHeader.vue
- src/router.js
- src/store/appType/actions.js
- src/views/AppDetails.vue
- tests/unit/specs/components/app/__snapshots__/AppDetailsHeader.spec.js.snap
- tests/unit/specs/views/AppDetails.spec.js
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
AppDetails view now fetch data from API
> Feat: app details from api

- src/api/appType.js
- src/components/app/AppDetailsComments.vue
- src/store/appType/actions.js
- src/views/AppDetails.vue
- tests/unit/specs/components/app/AppDetailsComments.spec.js
- tests/unit/specs/components/app/__snapshots__/AppDetailsComments.spec.js.snap
- tests/unit/specs/store/appType/actions.spec.js
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
- New Vuex actions to fetch comments data
- Comments on AppDetails view comments are fetched now through API
- Implemented tests
> Feat: Comments from api

- src/components/app/AppDetailsAbout.vue
- src/views/AppDetails.vue
- tests/unit/specs/views/AppDetails.spec.js
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
- App links are now a computed property
> Fix: app details links

- package.json
- src/api/appType.js
- src/components/AppGrid.vue
- src/components/app/AppDetailsComments.vue
- src/locales/en.json
- src/store/appType/actions.js
- tests/__mocks__/appMock.js
- tests/unit/specs/components/AppGrid.spec.js
- tests/unit/specs/components/__snapshots__/AppGrid.spec.js.snap
- tests/unit/specs/store/appType/actions.spec.js
- yarn.lock
- Call API method on install action
- Fixed and improved unit tests
- Updated locales
- Downgraded jest for compatibility reasons
> Feat: Install app from API

- src/api/appType.js
- src/api/myApps.js
- src/components/AppGrid.vue
- src/store/index.js
- src/store/myApps/actions.js
- src/store/myApps/index.js
- tests/unit/specs/components/AppGrid.spec.js
- tests/unit/specs/store/myApps/actions.spec.js
- tests/unit/specs/views/AppDetails.spec.js
- My apps from API
- Added tests
> Feat: my apps from api

- src/api/appType.js
- src/components/config/channels/WWC/Config.vue
- src/store/appType/actions.js
- src/utils/clean.js
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Config.spec.js.snap
- tests/unit/specs/store/appType/actions.spec.js
- Configuration of WWC now calls API
- Implemented tests
To be accomplished on future fixes:
- Show avatar image on file picker preview when already configured
> feat: wwc config with api

- src/components/app/AppDetailsAbout.vue
- src/components/app/AppDetailsHeader.vue
- src/locales/en.json
- src/locales/pt_br.json
- tests/unit/specs/components/app/__snapshots__/AppDetailsHeader.spec.js.snap
- Descriptions i18n keys now are fetched from the backend
> fix: app details description translations

- src/views/AppDetails.vue
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
- New metrics to app details banner
-  Integrations count and per app metric
> feat: new metrics to app details banner

- src/components/ColorPicker.vue
- Fixes selector placement to now appear on top left of screen
> fix: color picker selector placement

- src/components/config/channels/WWC/Config.vue
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Config.spec.js.snap
- Alert user on success and error cases
> Feat: Notification alert on save config action with success or error

- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/WWC/Simulator.vue
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Config.spec.js.snap
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Simulator.spec.js.snap
- Subtitle behavior on toggle
- Fullscreen button on toggle
- UnreadMessageCount on toggle
- Option to open and close chat on icon click
> Fix: Simulator behaviors

- src/components/Carousel.vue
- tests/unit/specs/components/__snapshots__/Carousel.spec.js.snap
- Banner text color
- Banner autoplay is active only if there is more than one element
> Fix: Banner autoplay and text color

- src/components/AddModal.vue
- src/components/AppGrid.vue
- src/components/app/AppDetailsHeader.vue
- src/views/AppDetails.vue
- tests/unit/specs/components/AddModal.spec.js
- tests/unit/specs/components/AppGrid.spec.js
- tests/unit/specs/components/__snapshots__/AddModal.spec.js.snap
- tests/unit/specs/components/app/AppDetailsHeader.spec.js
- tests/unit/specs/components/app/__snapshots__/AppDetailsHeader.spec.js.snap
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
- yarn.lock
- AddModal is now a component to be used in AppGrid and AppDetailsHeader without code duplication
> Improve: Add modal as component

- src/views/AppDetails.vue
- When changing the rating, now the component is rerendered with the new rating average
> Fix: Update rating after action

- src/views/AppDetails.vue
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
Hiding recommended section while new apps are created
> fix: hide recommended section

- src/components/AppGrid.vue
- src/components/Carousel.vue
- src/components/app/AppDetailsComments.vue
- src/components/app/AppDetailsHeader.vue
- src/components/config/channels/WWC/Config.vue
- src/components/loadings/AppGrid.vue
- src/components/loadings/Carousel.vue
- src/locales/en.json
- src/views/AppDetails.vue
- src/views/Discovery.vue
- src/views/loadings/AppDetails.vue
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
- tests/unit/specs/views/__snapshots__/Discovery.spec.js.snap
- Loading screens for grid and app details
- Removed unused category "tickets"
- Fixed some locales keys
> Feat: Loading screens

- package.json
- src/main.js
- yarn.lock
> Feat: Sentry

- src/components/AppGrid.vue
- tests/unit/specs/components/AppGrid.spec.js
- tests/unit/specs/components/__snapshots__/AppGrid.spec.js.snap
> Feat: Section icons

- src/components/config/channels/WWC/Config.vue
- New field `initPayload`
- `timeBetweenMessages` is now sent to backend
> Feat: Support to initPayload and timeBetweenMessages config

- package.json
- src/components/config/channels/WWC/Config.vue
- yarn.lock
- Modified `scriptCode` to `DataArea`
- Added button to copy `scriptCode` to clipboard
> Feat: WWC script copy to clipboard

- src/router.js
- After route change a postMessage to parent is fired with:
```
{
event: 'changePathname',
pathname: window.location.pathname,
}
```
> Feat: New postMessage with pathname after route change

- src/components/FileUpload.vue
- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/WWC/Simulator.vue
- src/locales/en.json
- tests/__mocks__/appMock.js
- tests/unit/specs/components/FileUpload.spec.js
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- File preview needed specific data to be like type and size to be displayed and added to vue-dropzone
> Fix: File upload preview

- src/components/AddModal.vue
- src/components/AppGrid.vue
- src/components/Carousel.vue
- src/components/ConfigModal.vue
- src/components/FileUpload.vue
- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/WWC/Simulator.vue
- src/locales/en.json
- src/locales/pt_br.json
- src/views/AppDetails.vue
- tests/unit/specs/components/Carousel.spec.js
- tests/unit/specs/components/__snapshots__/AddModal.spec.js.snap
- tests/unit/specs/components/__snapshots__/AppGrid.spec.js.snap
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Config.spec.js.snap
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Simulator.spec.js.snap
- tests/unit/specs/views/__snapshots__/AppDetails.spec.js.snap
- Banner click should now opens details page
- Edit and configure buttons are now redirect to app details page
- Fixed dropzone height when an invalid file is received
- Configure later button on WWC now closes the modal
- New alerto on script copy action
- WWC simulator now closes on close button click
- Fixed WWC icon background in configure modal
> Fix: Design review issues

- .github/workflows/build-integrations-webapp-dispatch-shared.yaml
- .github/workflows/build-integrations-webapp-push-tag-shared.yaml
Workflows related to new infra details.
> Add new workflows to build image

- package.json
- src/components/AddModal.vue
- src/components/AppGrid.vue
- src/components/app/AppDetailsAbout.vue
- src/components/config/channels/WWC/Config.vue
- src/locales/en.json
- src/locales/pt_br.json
- src/views/MyApps.vue
- tests/unit/specs/components/__snapshots__/AddModal.spec.js.snap
- tests/unit/specs/components/__snapshots__/AppGrid.spec.js.snap
- tests/unit/specs/components/app/__snapshots__/AppDetailsComments.spec.js.snap
- tests/unit/specs/views/__snapshots__/Discovery.spec.js.snap
- tests/unit/specs/views/__snapshots__/MyApps.spec.js.snap
Fixed issues:
- App Grid title spacing
- App Grid card drop down button type
- Hide useful links section there are no links
- My Apps view sections gap
- Weni Web Chat trigger message tool tip icon color
- Weni Web Chat error labels colors
- Missing locales
- Remove custom colors for modal buttons such as add and remove
> Fix: Design issues

- src/components/config/channels/whatsapp/Config.vue
- src/components/config/channels/whatsapp/components/ConversationsTable.vue
- src/components/config/channels/whatsapp/components/StatusIndicator.vue
- src/components/config/channels/whatsapp/components/tabs/ContactInfoTab.vue
- src/components/config/channels/whatsapp/components/tabs/ConversationsTab.vue
- src/components/config/channels/whatsapp/components/tabs/GeneralTab.vue
- src/components/config/channels/whatsapp/components/tabs/ProfileTab.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- tests/unit/specs/components/config/channels/whatsapp/Config.spec.js
- tests/unit/specs/components/config/channels/whatsapp/__snapshots__/Config.spec.js.snap
- tests/unit/specs/components/config/channels/whatsapp/components/ConversationsTable.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/__snapshots__/ConversationsTable.spec.js.snap
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/ContactInfoTab.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/ConversationsTab.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/GeneralTab.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/ProfileTab.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/__snapshots__/ContactInfoTab.spec.js.snap
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/__snapshots__/ConversationsTab.spec.js.snap
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/__snapshots__/GeneralTab.spec.js.snap
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/__snapshots__/ProfileTab.spec.js.snap
Refactor the WhatsApp Integration Config page component.
> Refactor: Whatsapp config

- src/components/config/DynamicForm.vue
- tests/unit/specs/components/config/DynamicForm.spec.js
- tests/unit/specs/components/config/__snapshots__/DynamicForm.spec.js.snap
Fixed issue where unnnic-select was misused and returned an incorrect key value.
> Fix: Dynamic form select options

- src/components/config/channels/WWC/Config.vue
- src/utils/files.js
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Config.spec.js.snap
New Files module to handle Base64 conversion and link/base64 images to a File object
> Feat: Files utils

- src/components/config/DynamicForm.vue
- src/components/config/channels/whatsapp/components/tabs/ProfileTab.vue
Max photo size limit is now 5Mb
> Feat: WhatsApp max photo size

- src/api/appType/whatsapp_cloud/index.js
- src/store/appType/index.js
- src/store/appType/whatsapp_cloud/actions.js
- src/store/appType/whatsapp_cloud/getters.js
- src/store/appType/whatsapp_cloud/index.js
- src/store/appType/whatsapp_cloud/mutations.js
- src/store/appType/whatsapp_cloud/state.js
- tests/unit/specs/store/appType/whatsapp_cloud/actions.spec.js
- tests/unit/specs/store/appType/whatsapp_cloud/getters.spec.js
- Vuex store implementation for WhatsApp Cloud.
> Feat: WhatsApp Cloud vuex store

- src/components/config/channels/whatsapp/Config.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- tests/unit/specs/components/config/channels/whatsapp/Config.spec.js
- tests/unit/specs/components/config/channels/whatsapp/__snapshots__/Config.spec.js.snap
- Added documentation links for WhatsApp
> Feat: WhatsApp description with doc links

- src/api/appType.js
- src/api/appType/whatsapp/index.js
- src/components/IntegrateButton.vue
- src/components/config/channels/whatsapp/Config.vue
- src/components/config/channels/whatsapp/components/tabs/ConversationsTab.vue
- src/components/config/channels/whatsapp/components/tabs/ProfileTab.vue
- src/store/appType/actions.js
- src/store/appType/channels/whatsapp/actions.js
- src/store/appType/channels/whatsapp/mutations.js
- src/store/appType/channels/whatsapp/state.js
- tests/unit/specs/components/IntegrateButton.spec.js
- tests/unit/specs/components/config/channels/whatsapp/Config.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/ConversationsTab.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/ProfileTab.spec.js
- tests/unit/specs/store/appType/actions.spec.js
- tests/unit/specs/store/appType/whatsapp/actions.spec.js
- tests/unit/specs/views/OtherApps.spec.js
- Moved all WhatsApp actions into the namespaced module
- Refactored WhatsApp actions with error and loading behavior
> Refactor: AppType WhatsApp Actions

- src/api/request.js
- src/components/AppGrid.vue
- src/components/IntegrateButton.vue
- src/components/app/AppDetailsHeader.vue
- src/components/config/channels/whatsapp/PhoneNumberSelection.vue
- src/store/auth/getters.js
- src/views/Discovery.vue
- src/views/MyApps.vue
- src/views/OtherApps.vue
- tests/unit/specs/components/AppGrid.spec.js
- tests/unit/specs/components/IntegrateButton.spec.js
- tests/unit/specs/components/app/AppDetailsHeader.spec.js
- tests/unit/specs/components/config/channels/whatsapp/PhoneNumberSelection.spec.js
- tests/unit/specs/store/auth/getters.spec.js
- tests/unit/specs/views/Discovery.spec.js
- tests/unit/specs/views/MyApps.spec.js
- tests/unit/specs/views/OtherApps.spec.js
- Use state instead of getters
- Remove unused getSelectedOrg getter
> Refactor: Auth store

- jest.config.js
- package.json
- src/main.js
- src/miragejs/factories/index.js
- src/miragejs/factories/template.js
- src/miragejs/factories/translation.js
- src/miragejs/models/index.js
- src/miragejs/routes/index.js
- src/miragejs/seeds/index.js
- src/miragejs/serializers/index.js
- src/miragejs/server.js
- yarn.lock
- Add MirageJs lib to mock API requests
> Feat: Miragejs

- src/store/appType/actions.js
- src/store/appType/channels/whatsapp/actions.js
- src/store/appType/channels/whatsapp_cloud/actions.js
- src/utils/sentry.js
- Added sentry error catching in WhatsApp endpoints and App CRUD endpoints
- Improved sentry `extra` field with response data
> Improve: Sentry coverage and extra payload

- src/components/config/channels/whatsapp/Config.vue
- src/components/config/channels/whatsapp/components/tabs/ConversationsTab.vue
- Close button not working
- Date preview not working on firefox browser
> Fix: WhatsApp Conversations Tab issues

- src/router.js
- Added lazy loading into routes
- Added WhatsApp templates routes for Base, Form and Table views
> Feat: WhatsApp Templates routes

- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- EN, ES and PT_BR locales for WhatsApp templates
> Feat: Whats App Templates locales

- src/components/whatsAppTemplates/FormTabs.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- Success alert on template translation successful creation
> Feat: Success feedback on translation creation

- src/store/appType/state.js
- Set default value of `loadingUpdateAppConfig` to false
> fix: default loadingUpdateAppConfig value

- src/components/whatsAppTemplates/FormTabContentButtons.vue
- src/components/whatsAppTemplates/FormTabs.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- tests/unit/specs/components/whatsAppTemplates/FormTabContentButtons.spec.js
- tests/unit/specs/components/whatsAppTemplates/FormTabs.spec.js
- Display `https://` on input prefix
- Force `https://` at button url on send
> Feat: WhatsApp Templates default button url https

- src/components/whatsAppTemplates/FormTabContent.vue
- src/components/whatsAppTemplates/FormTabs.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- tests/unit/specs/components/whatsAppTemplates/FormTabContent.spec.js
- tests/unit/specs/components/whatsAppTemplates/FormTabs.spec.js
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabContent.spec.js.snap
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabs.spec.js.snap
- Alert the input if the name already exists
- Prevent the form from being submited
> Feat: Check if template name already exists before save

- package.json
- src/components/whatsAppTemplates/FormTabContentBody.vue
- src/components/whatsAppTemplates/InputEditor.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- src/utils/countTemplateVariables.js
- tests/unit/specs/components/whatsAppTemplates/FormTabContentBody.spec.js
- tests/unit/specs/components/whatsAppTemplates/InputEditor.spec.js
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabContent.spec.js.snap
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabContentBody.spec.js.snap
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabContentFooter.spec.js.snap
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabs.spec.js.snap
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/InputEditor.spec.js.snap
- yarn.lock
- Display errors on template body text-area
- Close emoji-picker on outside click
> Feat: Template message body content improvements

- src/components/AppGrid.vue
- src/views/Discovery.vue
- tests/unit/specs/components/AppGrid.spec.js
- tests/unit/specs/components/__snapshots__/AppGrid.spec.js.snap
- tests/unit/specs/views/Discovery.spec.js
- tests/unit/specs/views/__snapshots__/Discovery.spec.js.snap
- When `create_app` is provided as query param on the Discovery page, automatically try to start it's integration process
> Feat: Create app from query params

- src/components/AppGrid.vue
- Fixed pagination component positioning adding a margin offset
> Fix: Pagination component margin offset

- src/api/appType/generic/index.js
- src/store/appType/actions.js
- tests/unit/specs/store/appType/actions.spec.js
- Update to use generic apps endpoint: `/api/v1/apptypes/generic/apptypes`
> Feat: Use new Generic apps list endpoint

- src/App.vue
- Increase bottom margin
- Increase right margin on firefox
> Fix: Survey toggle positioning

- src/api/appType/whatsapp/index.js
- src/components/config/channels/whatsapp/Config.vue
- src/components/config/channels/whatsapp/components/tabs/WebhookTab.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- src/store/appType/channels/whatsapp/actions.js
- src/store/appType/channels/whatsapp/mutations.js
- src/store/appType/channels/whatsapp/state.js
- tests/unit/specs/components/config/channels/whatsapp/__snapshots__/Config.spec.js.snap
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/WebhookTab.spec.js
- tests/unit/specs/components/config/channels/whatsapp/components/tabs/__snapshots__/WebhookTab.spec.js.snap
- tests/unit/specs/store/appType/whatsapp/actions.spec.js
- New webhook tab for whatsapp applications
- Webhook method, url and headers can be configured
> Feat: WhatsApp Webhook Tab

- src/components/whatsAppTemplates/TranslationSampleForm.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- tests/unit/specs/components/whatsAppTemplates/TranslationSampleForm.spec.js
- Increase template max sample size to 16Mb
> Feat: Increase templates max sample size

- src/components/whatsAppTemplates/FormTabContent.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- Remove `TRANSACTIONAL` and `OTP`categories
- Add `UTILTY` and `AUTHENTICATION` categories
> Feat: Update templates categories with authentication and utilty

- src/components/config/external/omie/Config.vue
- Fix icon height and added vertical alignment
> Fix: Omie icon dimension and positioning

- .github/workflows/test-and-build.yml
- README.md
- jest.config.js
- Added codecov integration to CI
- Updated README with codecov and build badges
> Feat: Add codecov to ci

- src/components/whatsAppTemplates/FormTabContentHeader.vue
- src/components/whatsAppTemplates/FormTabs.vue
- Fix button incorrect button condition causing to sometimes have a ghost undefined button
- Fix misaligned media buttons
> Fix: WhatsApp Templates preview

- src/components/OnboardModal.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- tests/unit/specs/components/__snapshots__/OnboardModal.spec.js.snap
- Updated locales with fixed texts
- Updated fonts and spacing for the onboard modals
> Fix: Onboard Modal design issues

- src/components/AppGrid.vue
- src/components/EmptyApps.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- src/views/Discovery.vue
- src/views/MyApps.vue
- tests/unit/specs/components/AppGrid.spec.js
- tests/unit/specs/views/Discovery.spec.js
- tests/unit/specs/views/MyApps.spec.js
- tests/unit/specs/views/__snapshots__/Discovery.spec.js.snap
- tests/unit/specs/views/__snapshots__/MyApps.spec.js.snap
- Added search bar for discovery and my apps pages
> Feat: Discovery and My Apps search bar

- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- src/router.js
- src/views/whatsAppTemplates/Base.vue
- src/views/whatsAppTemplates/Table.vue
- tests/unit/specs/views/whatsAppTemplates/Base.spec.js
- tests/unit/specs/views/whatsAppTemplates/Table.spec.js
- tests/unit/specs/views/whatsAppTemplates/__snapshots__/Table.spec.js.snap
- Better handler for WhatsApp templates crumbs
> Fix: Whatsapp templates crumbs

- src/App.vue
- src/components/config/channels/whatsapp/Config.vue
- src/components/config/channels/whatsapp/components/tabs/WebhookTab.vue
- src/components/whatsAppTemplates/FormHeader.vue
- src/components/whatsAppTemplates/FormTabContent.vue
- src/components/whatsAppTemplates/FormTabs.vue
- src/views/MyApps.vue
- src/views/whatsAppTemplates/Base.vue
- src/views/whatsAppTemplates/Form.vue
- src/views/whatsAppTemplates/Table.vue
- tests/unit/specs/components/config/channels/whatsapp/__snapshots__/Config.spec.js.snap
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabContent.spec.js.snap
- tests/unit/specs/components/whatsAppTemplates/__snapshots__/FormTabs.spec.js.snap
- tests/unit/specs/views/__snapshots__/App.spec.js.snap
- tests/unit/specs/views/__snapshots__/MyApps.spec.js.snap
- Fixes scroll not appearing for some pages/components in firefox
> Fix: Scroll issues on firefox

- src/components/config/bi_tools/power_bi/Config.vue
- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/generic/Config.vue
- src/components/config/channels/telegram/Config.vue
- src/components/config/channels/wpp_demo/Preview.vue
- src/components/config/external/omie/Config.vue
- tests/unit/specs/components/config/bi_tools/power_bi/__snapshots__/Config.spec.js.snap
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Config.spec.js.snap
- tests/unit/specs/components/config/external/omie/__snapshots__/Config.spec.js.snap
- Previous PR only fixed WhatsApp related scroll pages, this one fixes WWC, Telegram, WhatsApp Demo, Power Bi, Omie and Generic Apps.
> Fix: Scroll issues on firefox for all apps

- README.md
Adding new README to the project, as well as the environment variables needed to run it locally.
> Feat: Readme template

- src/components/whatsAppCatalogs/List.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
Create modal with new text for when the user enables a catalog without having disabled the old one.
> [FLOWS-109] fix: active catalog modal

- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/WWC/Simulator.vue
- tests/unit/specs/components/config/channels/WWC/Config.spec.js
- tests/unit/specs/components/config/channels/WWC/__snapshots__/Config.spec.js.snap
> Fix: design reviews v1.1

- src/components/config/channels/WWC/Config.vue
> Fix: design review 29/12

- src/components/Carousel/styles.scss
- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/whatsapp/Setup.vue
- src/utils/plugins/fb.js
- src/views/Insights/styles.scss
- tests/unit/specs/components/config/channels/whatsapp/Setup.spec.js
- Updates the embed signup flow in WhatsApp setup, now removing the unnecessary phone number selection stage
- Fixed some css flex-start and flex-end issues that prevented the build
> Feat: New WhatsApp Embed Signup

- src/components/AddModal/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Upgrade Vue version.
Upgrade Add Modal inputs to vue3.
> [FLOWS_1495] - Update AddModal component.

- src/components/app/AppDetailsComments.vue
- src/components/app/AppDetailsHeader.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Upgrade Vue version.
Change store from vuex to pinia.
> [FLOWS_1495] - Update App components.

- src/components/config/bi_tools/power_bi/Config.vue
- src/components/config/channels/generic/Config.vue
- src/components/config/channels/whatsapp/components/tabs/loadings/ProfileTab.vue
- yarn.lock
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Upgrade vue version.
Remove skeleton-loading.
> fix: remove skeleton-loading

- src/views/Discovery/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix onboardModal.
Comment onboardModal uses.
> fix: comment onboarmodal

- src/components/whatsAppTemplates/FormTabContent.vue
- src/components/whatsAppTemplates/FormTabs.vue
- src/components/whatsAppTemplates/Table.vue
- src/components/whatsAppTemplates/TranslationSampleForm.vue
- src/stores/modules/appType/channels/whatsapp.store.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix whatsapp template form.
Remove reset store before unmount the component and fix table date picker.
> Fix: Whatsapp Templates

- package.json
- src/views/AppDetails/index.vue
- src/views/Discovery/index.vue
- src/views/MyApps/index.vue
- src/views/OtherApps/index.vue
- src/views/TemplateDetails/index.vue
- src/views/whatsAppTemplates/Form.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix bugs from vue3 first migration.
Fix bugs from vue3 first migration on views files.
> [FLOWS_1495] - Update Views

- src/components/whatsAppCatalogs/CatalogList.vue
- src/components/whatsAppCatalogs/ProductList.vue
- src/components/whatsAppTemplates/Table.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Pagination was not working properly on those components
Used correct variable on page change
> fix: pagination

- CHANGELOG.md
- package.json
- src/components/config/channels/WWC/Config.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Enable the avatar change on WWC Config.
Add missing filheChange prop.
> [HT34799] - Fix wwc change avatar

- src/api/appType/ecommerce/index.js
- src/components/config/ecommerce/vtex/Config.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
- src/stores/modules/appType/ecommerce/ecommerce.store.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Enable sellers sync.
Added the selection of sellers on VTEX Config.
> [FLOWS _2315] - Sync VTEX Sellers

- CHANGELOG.md
- package.json
- src/components/config/channels/whatsapp/components/tabs/ProfileTab.vue
- src/components/config/channels/whatsapp/components/tabs/WebhookTab.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix WhatsApp profile and webhoot tabs;
Add optional chaining on profile props.
> [FLOWS] - Fix WhatsApp profile and webhoot tabs

- src/components/config/channels/whatsapp/Setup.vue
- src/stores/modules/appType/channels/whatsapp_cloud.store.js
- src/utils/sentry.js
* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
Any error that occurs during this process need to be sent to sentry
Manually sending errors from the whatsapp cloud signup process to sentry
> [FLOWS-2706] Feat: manually send errors that occurs on whatsapp signup process

- src/components/config/channels/whatsapp/Setup.vue
* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
Updated session info listener with latests documentation standards
Better handling of facebook domains and embedded signup errors
> feat: update session info listener handler

- docker-entrypoint.sh
- src/main.js
- src/utils/plugins/Hotjar.js
Add hotjar configuration.
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Set Hotjar on Integrations Webapp.
Added hotjar config.
> [FLOWS-2453] - Add Hotjar Config

- src/components/config/channels/whatsapp/components/tabs/WebhookTab.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix webhook URL validation.
Added a url regex to the new unnnic input check.
> [HT36149] - Fix: Webhook regex

- src/components/config/channels/whatsapp/components/tabs/WebhookTab.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix Webhook for WhatsApp Channel in Integrations Not Working.
Fix unnnicCallAlert props.
> [FLOWS-2888] - Fix: Webhook for WhatsApp Channel in Integrations Not Working.

- package.json
- src/components/config/channels/generic/Config.vue
- yarn.lock
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Selector was not being rendered and could not be modified
Fixed the options label property and the value return for the dynamic form component
> [FLOWS-2924] Fix: dynamic form select input

- src/components/config/DynamicForm.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix dynamic form translations.
Get form translations.
> [FLOWS-2964] Fix: dynamic form translations

- src/components/config/channels/WWC/Config.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Web Chat does not update preferences.
Update keepHistory prop.
> [FLOWS-3005] - Fix: Web Chat does not update preferences.

- src/components/config/channels/whatsapp/components/tabs/WebhookTab.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix WhatsApp Webhook method;
Fix: WhatsApp Webhook method;
> [FLOWS] - Fix: WhatsApp Webhook method;

- src/components/config/ecommerce/vtex/Config.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Enable save when VTEX ADS is changed.
Changed disableSave prop.
> [FLOWS] - Fix: Enable save when VTEX ADS is changed

- CHANGELOG.md
- package.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix vtex ads and insights.
Update version.
> [RS-182] - Release 2.2.2

- src/components/config/channels/WWC/Config.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix WWC config modal.
Handle keepHistory prop when there isn`t storage param.
> [RS] - Fix: Weni Web Chat config modal

- CHANGELOG.md
- package.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Keep insights state after refreshing the page and update chart at period change.
Bum version to 2.2.4.
> [RS] - Fix: insights persisted state

- CHANGELOG.md
- package.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Handle update grid.
Bump version.
> [RS-242] - Fix: Configured Weni Chats card doesn't update.

- .github/workflows/crowdin-download.yaml
- .github/workflows/crowdin-upload.yaml
- crowdin.yml
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In order to implement Crowdin for better management of texts and translations.
* Adds Crowdin integrations.
> [RS-262] Crowdin Implementation

- src/components/config/channels/whatsapp/components/tabs/ConversationsTab.vue
- src/tests/components/config/ConfigModal.spec.js
- src/tests/components/config/DynamicForm.spec.js
- src/tests/components/config/bi_tools/power_bi/Config.spec.js
- src/tests/components/config/channels/WWC/Config.spec.js
- src/tests/components/config/channels/facebook/Config.spec.js
- src/tests/components/config/channels/facebook/Setup.spec.js
- src/tests/components/config/channels/facebook/__snapshots__/Config.spec.js.snap
- src/tests/components/config/channels/generic/Config.spec.js
- src/tests/components/config/channels/instagram/Config.spec.js
- src/tests/components/config/channels/telegram/Config.spec.js
- src/tests/components/config/channels/telegram/__snapshots__/Config.spec.js.snap
- src/tests/components/config/channels/whatsapp/Config.spec.js
- src/tests/components/config/channels/whatsapp/Setup.spec.js
- src/tests/components/config/channels/whatsapp/components/CreateCatalogModalContent.spec.js
- src/tests/components/config/channels/whatsapp/components/StatusIndicator.spec.js
- src/tests/components/config/channels/whatsapp/components/tabs/AccountTab.spec.js
- src/tests/components/config/channels/whatsapp/components/tabs/ConversationsTab.spec.js
- src/tests/components/config/channels/whatsapp/components/tabs/ProfileTab.spec.js
- src/tests/components/config/channels/whatsapp/components/tabs/WebhookTab.spec.js
- src/tests/components/config/channels/whatsapp/components/tabs/__snapshots__/ConversationsTab.spec.js.snap
- src/tests/components/config/channels/whatsapp/loadings/PhoneNumberSelection.spec.js
- src/tests/components/config/channels/wpp_demo/Config.spec.js
- src/tests/components/config/channels/wpp_demo/Preview.spec.js
- src/tests/components/config/ecommerce/vtex/Config.spec.js
- src/tests/components/config/ecommerce/vtex/ConnectCatalogModalContent.spec.js
- src/tests/components/config/ecommerce/vtex/Setup.spec.js
- src/tests/views/Insights.spec.js
- src/tests/views/__snapshots__/OtherApps.spec.js.snap
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Add config components tests.
Added config components tests.
> [RS-182] - Add components config tests.

- src/tests/components/TemplateDetails/Summary.spec.js
- src/tests/views/Insights.spec.js
- src/tests/views/__snapshots__/OtherApps.spec.js.snap
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Add whatsapp template details tests.
Added whatsapp template details tests.
> [RS-182] - Add whatsapp template details tests.

- src/tests/components/WhatsAppTemplates/FormHeader.spec.js
- src/tests/components/WhatsAppTemplates/FormTabContentBody.spec.js
- src/tests/components/WhatsAppTemplates/FormTabContentButtons.spec.js
- src/tests/components/WhatsAppTemplates/FormTabContentFooter.spec.js
- src/tests/components/WhatsAppTemplates/FormTabContentHeader.spec.js
- src/tests/components/WhatsAppTemplates/FormTabs.spec.js
- src/tests/components/WhatsAppTemplates/InputEditor.spec.js
- src/tests/components/WhatsAppTemplates/Table.spec.js
- src/tests/components/WhatsAppTemplates/loadings/FormHeaderLoading.spec.js
- src/tests/components/WhatsAppTemplates/loadings/TableHeaderLoading.spec.js
- src/tests/components/WhatsAppTemplates/loadings/TableLoading.spec.js
- src/tests/views/Insights.spec.js
- src/tests/views/__snapshots__/OtherApps.spec.js.snap
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Add whatsapp templates tests.
Added whatsapp templates tests.
> [RS-182] - Add whatsapp templates tests.

- src/tests/components/whatsappCatalogs/CatalogCard.spec.js
- src/tests/components/whatsappCatalogs/CatalogList.spec.js
- src/tests/components/whatsappCatalogs/ProductList.spec.js
- src/tests/views/Insights.spec.js
- src/tests/views/__snapshots__/OtherApps.spec.js.snap
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Add whatsapp catalogs tests.
Added whatsapp catalogs tests.
> [RS-182] - Add whatsapp catalogs tests.

- src/tests/components/AddModal.spec.js
- src/tests/components/AppGrid.spec.js
- src/tests/components/AppModal.spec.js
- src/tests/components/BaseInput.spec.js
- src/tests/components/Carousel.spec.js
- src/tests/components/ColorPicker.spec.js
- src/tests/components/EmptyApps.spec.js
- src/tests/components/IntegrateButton.spec.js
- src/tests/components/LoadingButton.spec.js
- src/tests/components/NavBar.spec.js
- src/tests/components/Navigator.spec.js
- src/tests/components/OnboardModal.spec.js
- src/tests/components/Survey.spec.js
- src/tests/components/__snapshots__/AddModal.spec.js.snap
- src/tests/components/__snapshots__/AppGrid.spec.js.snap
- src/tests/components/__snapshots__/AppModal.spec.js.snap
- src/tests/components/__snapshots__/EmptyApps.spec.js.snap
- src/tests/components/__snapshots__/NavBar.spec.js.snap
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Add whatsapp components tests.
Added whatsapp components tests.
> [RS-182] - Add whatsapp components tests.

- CHANGELOG.md
- package.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.2.6.
> [RS] - Release: 2.2.6

- src/components/config/channels/WWC/Config.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Add startFullScreen and embedded props to wwc config.
Added startFullScreen and embedded props to wwc config.
> [RS - 327] Feat: new props

- src/components/config/ecommerce/vtex/Config.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix VTEX Config disable sellers.
Fixed VTEX Config disable sellers.
> [RS] Fix: VTEX Config disable sellers

- CHANGELOG.md
- package.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.2.7.
> [RS - 327] Release: 2.2.7

- nginx.conf
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In order to bring more security to the Integrations module, this PR defines the configuration rules for the Content-Security-Policy header.
* Adds `Content-Security-Policy` settings header.
> [RS-344] Content-Security-Policy Settings Header

- src/components/config/ecommerce/vtex/Config.vue
- src/tests/components/config/ecommerce/vtex/Config.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Allow sellers selection after Vtex ADS changed.
> [RS] Fix: VTEX config

- CHANGELOG.md
- package.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Release 2.2.8.
> [RS] Release: 2.2.8

- nginx.conf
- package.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds Facebook Domain to `Content-Security-Policy`.
> [HS-379] Bug: Content-Security-Policy Missing Facebook Domain

- nginx.conf
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix security police to allow emojis and photo update.
> [HS-400] Fix: Unable to See Emojis in the WhatsApp Template

- nginx.conf
- src/components/config/channels/WWC/Config.vue
- src/components/config/channels/email/Setup.vue
- src/tests/components/config/channels/WWC/Config.spec.js
- src/tests/store/modules/appType/appType.spec.js
- src/tests/views/__snapshots__/OtherApps.spec.js.snap
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The avatar upload in Weni Webchat was blocking subsequent changes.
The conversion of files to base64 has been fixed.
> [HS] Fix: Weni WebChat avatar upload

- nginx.conf
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
> [HS] Fix: security policy

- docker-entrypoint.sh
- package.json
- src/components/config/channels/email/Setup.vue
- src/tests/components/config/ecommerce/vtex/Setup.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Uses Gmail Redirect URI as env var.
> Uses Gmail Redirect URI as Env Var

- src/components/whatsAppTemplates/FormTabContentButtons.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
> [ HT37540 ] Fix: template form buttons

- CHANGELOG.md
- package.json
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
> release: 2.2.21

- src/components/whatsAppTemplates/FormTabs.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
> [HS] Fix: button URL validation

- src/components/whatsAppTemplates/FormTabs.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
> [HS] Fix: empty url validation

- .github/workflows/build-integrations-webapp-push-tag-shared.yaml
- Dockerfile
- docker/file_handler.sh
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Add script in posix shell to remove old files and use in Dockerfile
Implementation a posix shell script to manage and remove old files based on unix timestamps since the base image only provides posix shell. The script reads a list of timestamps, calculates which files to remove and manages this list. Modified the Dockerfile to use this script specifically for css files cleanup, providing an solution without additional dependencies.
> Cloud 2175

- nginx.conf
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Improve security to prevent future exploitation of vulnerabilities that could be targeted by an XSS attack and ensure that any pages on our sites that accept user input filter out code inputs such as HTML and JavaScript.
- Removal of headers injected directly into the nginx file. 
- The removed headers will be added to kubernetes via configmap. 
> add header of security

- Dockerfile
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Adds old file fix
> fix-hotjar

- .github/workflows/build-integrations-webapp-push-tag-shared.yaml
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Changing the workflow so that it becomes reusable and simpler to implement
> change workflow to reusable-workflow

- .github/workflows/build-integrations-webapp-push-tag-shared.yaml
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Reusing workflows
> Reusing workflows

- .github/workflows/build-integrations-webapp-push-tag-shared.yaml
- src/utils/env.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fixes the deploy file action.
> Fixes the Deploy Action

- src/components/config/ecommerce/vtex/Config.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
This PR adds the option to select all sellers at once and removes the previous block of selecting only 5 sellers.
* Adds the option to select all sellers at once;
* Removes block of selecting more than 5 sellers.
> [HS-1072] VTEX Sellers: Select All Sellers at Once

- src/api/appType/ecommerce/index.js
- src/components/config/channels/whatsapp/components/tabs/AccountTab.vue
- src/components/config/ecommerce/vtex/Config.vue
- src/locales/en.json
- src/locales/es_es.json
- src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Updates link catalog endpoint;
> [HS-1071] Catalog: Updates Endpoint for Linking Catalog
